services:
  app:
    build: .
    runtime: nvidia
    ports:
      - "8979:8979"
    volumes:
      - ./speakers:/usr/local/app/speakers  # Mount speakers to /root/speakers
      - ./model:/usr/local/app/model      # Mount model to /root/model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
