services:
  app:
    build: .
    runtime: nvidia
    ports:
      - "8979:8979"
   volumes:
      - ./speakers:/root/speakers  # Mount speakers to /root/speakers
      - ./model:/root/model      # Mount model to /root/model
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
